<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Auto generated seeder file.
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('countries')->truncate();
        
        \DB::table('countries')->insert([
            ['id' => 1,'name' => 'Andorra','code' => 'ad','active' => 1],
            ['id' => 2,'name' => 'United Arab Emirates','code' => 'ae','active' => 1],
            ['id' => 3,'name' => 'Afghanistan','code' => 'af','active' => 1],
            ['id' => 4,'name' => 'Antigua and Barbuda','code' => 'ag','active' => 1],
            ['id' => 5,'name' => 'Anguilla','code' => 'ai','active' => 1],
            ['id' => 6,'name' => 'Albania','code' => 'al','active' => 1],
            ['id' => 7,'name' => 'Armenia','code' => 'am','active' => 1],
            ['id' => 8,'name' => 'Netherlands Antilles','code' => 'an','active' => 1],
            ['id' => 9,'name' => 'Angola','code' => 'ao','active' => 1],
            ['id' => 10,'name' => 'Argentina','code' => 'ar','active' => 1],
            ['id' => 11,'name' => 'Austria','code' => 'at','active' => 1],
            ['id' => 12,'name' => 'Australia','code' => 'au','active' => 1],
            ['id' => 13,'name' => 'Aruba','code' => 'aw','active' => 1],
            ['id' => 14,'name' => 'Azerbaijan','code' => 'az','active' => 1],
            ['id' => 15,'name' => 'Bosnia and Herzegovina','code' => 'ba','active' => 1],
            ['id' => 16,'name' => 'Barbados','code' => 'bb','active' => 1],
            ['id' => 17,'name' => 'Bangladesh','code' => 'bd','active' => 1],
            ['id' => 18,'name' => 'Belgium','code' => 'be','active' => 1],
            ['id' => 19,'name' => 'Burkina Faso','code' => 'bf','active' => 1],
            ['id' => 20,'name' => 'Bulgaria','code' => 'bg','active' => 1],
            ['id' => 21,'name' => 'Bahrain','code' => 'bh','active' => 1],
            ['id' => 22,'name' => 'Burundi','code' => 'bi','active' => 1],
            ['id' => 23,'name' => 'Benin','code' => 'bj','active' => 1],
            ['id' => 24,'name' => 'Bermuda','code' => 'bm','active' => 1],
            ['id' => 25,'name' => 'Brunei Darussalam','code' => 'bn','active' => 1],
            ['id' => 26,'name' => 'Bolivia','code' => 'bo','active' => 1],
            ['id' => 27,'name' => 'Brazil','code' => 'br','active' => 1],
            ['id' => 28,'name' => 'Bahamas','code' => 'bs','active' => 1],
            ['id' => 29,'name' => 'Bhutan','code' => 'bt','active' => 1],
            ['id' => 30,'name' => 'Botswana','code' => 'bw','active' => 1],
            ['id' => 31,'name' => 'Belarus','code' => 'by','active' => 1],
            ['id' => 32,'name' => 'Belize','code' => 'bz','active' => 1],
            ['id' => 33,'name' => 'Canada','code' => 'ca','active' => 1],
            ['id' => 34,'name' => 'Cocos (Keeling) Islands','code' => 'cc','active' => 1],
            ['id' => 35,'name' => 'Democratic Republic of the Congo','code' => 'cd','active' => 1],
            ['id' => 36,'name' => 'Central African Republic','code' => 'cf','active' => 1],
            ['id' => 37,'name' => 'Congo','code' => 'cg','active' => 1],
            ['id' => 38,'name' => 'Switzerland','code' => 'ch','active' => 1],
            ['id' => 39,'name' => 'Cote D\'Ivoire (Ivory Coast)','code' => 'ci','active' => 1],
            ['id' => 40,'name' => 'Cook Islands','code' => 'ck','active' => 1],
            ['id' => 41,'name' => 'Chile','code' => 'cl','active' => 1],
            ['id' => 42,'name' => 'Cameroon','code' => 'cm','active' => 1],
            ['id' => 43,'name' => 'China','code' => 'cn','active' => 1],
            ['id' => 44,'name' => 'Colombia','code' => 'co','active' => 1],
            ['id' => 45,'name' => 'Costa Rica','code' => 'cr','active' => 1],
            ['id' => 46,'name' => 'Cuba','code' => 'cu','active' => 1],
            ['id' => 47,'name' => 'Cape Verde','code' => 'cv','active' => 1],
            ['id' => 48,'name' => 'Christmas Island','code' => 'cx','active' => 1],
            ['id' => 49,'name' => 'Cyprus','code' => 'cy','active' => 1],
            ['id' => 50,'name' => 'Czech Republic','code' => 'cz','active' => 1],
            ['id' => 51,'name' => 'Germany','code' => 'de','active' => 1],
            ['id' => 52,'name' => 'Djibouti','code' => 'dj','active' => 1],
            ['id' => 53,'name' => 'Denmark','code' => 'dk','active' => 1],
            ['id' => 54,'name' => 'Dominica','code' => 'dm','active' => 1],
            ['id' => 55,'name' => 'Dominican Republic','code' => 'do','active' => 1],
            ['id' => 56,'name' => 'Algeria','code' => 'dz','active' => 1],
            ['id' => 57,'name' => 'Ecuador','code' => 'ec','active' => 1],
            ['id' => 58,'name' => 'Estonia','code' => 'ee','active' => 1],
            ['id' => 59,'name' => 'Egypt','code' => 'eg','active' => 1],
            ['id' => 60,'name' => 'Western Sahara','code' => 'eh','active' => 1],
            ['id' => 61,'name' => 'Eritrea','code' => 'er','active' => 1],
            ['id' => 62,'name' => 'Spain','code' => 'es','active' => 1],
            ['id' => 63,'name' => 'Ethiopia','code' => 'et','active' => 1],
            ['id' => 64,'name' => 'Finland','code' => 'fi','active' => 1],
            ['id' => 65,'name' => 'Fiji','code' => 'fj','active' => 1],
            ['id' => 66,'name' => 'Falkland Islands (Malvinas)','code' => 'fk','active' => 1],
            ['id' => 67,'name' => 'Federated States of Micronesia','code' => 'fm','active' => 1],
            ['id' => 68,'name' => 'Faroe Islands','code' => 'fo','active' => 1],
            ['id' => 69,'name' => 'France','code' => 'fr','active' => 1],
            ['id' => 70,'name' => 'Gabon','code' => 'ga','active' => 1],
            ['id' => 71,'name' => 'Great Britain (UK)','code' => 'gb','active' => 1],
            ['id' => 72,'name' => 'Grenada','code' => 'gd','active' => 1],
            ['id' => 73,'name' => 'Georgia','code' => 'ge','active' => 1],
            ['id' => 74,'name' => 'French Guiana','code' => 'gf','active' => 1],
            ['id' => 75,'name' => 'NULL','code' => 'gg','active' => 1],
            ['id' => 76,'name' => 'Ghana','code' => 'gh','active' => 1],
            ['id' => 77,'name' => 'Gibraltar','code' => 'gi','active' => 1],
            ['id' => 78,'name' => 'Greenland','code' => 'gl','active' => 1],
            ['id' => 79,'name' => 'Gambia','code' => 'gm','active' => 1],
            ['id' => 80,'name' => 'Guinea','code' => 'gn','active' => 1],
            ['id' => 81,'name' => 'Guadeloupe','code' => 'gp','active' => 1],
            ['id' => 82,'name' => 'Equatorial Guinea','code' => 'gq','active' => 1],
            ['id' => 83,'name' => 'Greece','code' => 'gr','active' => 1],
            ['id' => 84,'name' => 'S. Georgia and S. Sandwich Islands','code' => 'gs','active' => 1],
            ['id' => 85,'name' => 'Guatemala','code' => 'gt','active' => 1],
            ['id' => 86,'name' => 'Guinea-Bissau','code' => 'gw','active' => 1],
            ['id' => 87,'name' => 'Guyana','code' => 'gy','active' => 1],
            ['id' => 88,'name' => 'Hong Kong','code' => 'hk','active' => 1],
            ['id' => 89,'name' => 'Honduras','code' => 'hn','active' => 1],
            ['id' => 90,'name' => 'Croatia (Hrvatska)','code' => 'hr','active' => 1],
            ['id' => 91,'name' => 'Haiti','code' => 'ht','active' => 1],
            ['id' => 92,'name' => 'Hungary','code' => 'hu','active' => 1],
            ['id' => 93,'name' => 'Indonesia','code' => 'id','active' => 1],
            ['id' => 94,'name' => 'Ireland','code' => 'ie','active' => 1],
            ['id' => 95,'name' => 'Israel','code' => 'il','active' => 1],
            ['id' => 96,'name' => 'India','code' => 'in','active' => 1],
            ['id' => 97,'name' => 'Iraq','code' => 'iq','active' => 1],
            ['id' => 98,'name' => 'Iran','code' => 'ir','active' => 1],
            ['id' => 99,'name' => 'Iceland','code' => 'is','active' => 1],
            ['id' => 100,'name' => 'Italy','code' => 'it','active' => 1],
            ['id' => 101,'name' => 'Jamaica','code' => 'jm','active' => 1],
            ['id' => 102,'name' => 'Jordan','code' => 'jo','active' => 1],
            ['id' => 103,'name' => 'Japan','code' => 'jp','active' => 1],
            ['id' => 104,'name' => 'Kenya','code' => 'ke','active' => 1],
            ['id' => 105,'name' => 'Kyrgyzstan','code' => 'kg','active' => 1],
            ['id' => 106,'name' => 'Cambodia','code' => 'kh','active' => 1],
            ['id' => 107,'name' => 'Kiribati','code' => 'ki','active' => 1],
            ['id' => 108,'name' => 'Comoros','code' => 'km','active' => 1],
            ['id' => 109,'name' => 'Saint Kitts and Nevis','code' => 'kn','active' => 1],
            ['id' => 110,'name' => 'Korea (North)','code' => 'kp','active' => 1],
            ['id' => 111,'name' => 'Korea (South)','code' => 'kr','active' => 1],
            ['id' => 112,'name' => 'Kuwait','code' => 'kw','active' => 1],
            ['id' => 113,'name' => 'Cayman Islands','code' => 'ky','active' => 1],
            ['id' => 114,'name' => 'Kazakhstan','code' => 'kz','active' => 1],
            ['id' => 115,'name' => 'Laos','code' => 'la','active' => 1],
            ['id' => 116,'name' => 'Lebanon','code' => 'lb','active' => 1],
            ['id' => 117,'name' => 'Saint Lucia','code' => 'lc','active' => 1],
            ['id' => 118,'name' => 'Liechtenstein','code' => 'li','active' => 1],
            ['id' => 119,'name' => 'Sri Lanka','code' => 'lk','active' => 1],
            ['id' => 120,'name' => 'Liberia','code' => 'lr','active' => 1],
            ['id' => 121,'name' => 'Lesotho','code' => 'ls','active' => 1],
            ['id' => 122,'name' => 'Lithuania','code' => 'lt','active' => 1],
            ['id' => 123,'name' => 'Luxembourg','code' => 'lu','active' => 1],
            ['id' => 124,'name' => 'Latvia','code' => 'lv','active' => 1],
            ['id' => 125,'name' => 'Libya','code' => 'ly','active' => 1],
            ['id' => 126,'name' => 'Morocco','code' => 'ma','active' => 1],
            ['id' => 127,'name' => 'Monaco','code' => 'mc','active' => 1],
            ['id' => 128,'name' => 'Moldova','code' => 'md','active' => 1],
            ['id' => 129,'name' => 'Madagascar','code' => 'mg','active' => 1],
            ['id' => 130,'name' => 'Marshall Islands','code' => 'mh','active' => 1],
            ['id' => 131,'name' => 'Macedonia','code' => 'mk','active' => 1],
            ['id' => 132,'name' => 'Mali','code' => 'ml','active' => 1],
            ['id' => 133,'name' => 'Myanmar','code' => 'mm','active' => 1],
            ['id' => 134,'name' => 'Mongolia','code' => 'mn','active' => 1],
            ['id' => 135,'name' => 'Macao','code' => 'mo','active' => 1],
            ['id' => 136,'name' => 'Northern Mariana Islands','code' => 'mp','active' => 1],
            ['id' => 137,'name' => 'Martinique','code' => 'mq','active' => 1],
            ['id' => 138,'name' => 'Mauritania','code' => 'mr','active' => 1],
            ['id' => 139,'name' => 'Montserrat','code' => 'ms','active' => 1],
            ['id' => 140,'name' => 'Malta','code' => 'mt','active' => 1],
            ['id' => 141,'name' => 'Mauritius','code' => 'mu','active' => 1],
            ['id' => 142,'name' => 'Maldives','code' => 'mv','active' => 1],
            ['id' => 143,'name' => 'Malawi','code' => 'mw','active' => 1],
            ['id' => 144,'name' => 'Mexico','code' => 'mx','active' => 1],
            ['id' => 145,'name' => 'Malaysia','code' => 'my','active' => 1],
            ['id' => 146,'name' => 'Mozambique','code' => 'mz','active' => 1],
            ['id' => 147,'name' => 'Namibia','code' => 'na','active' => 1],
            ['id' => 148,'name' => 'New Caledonia','code' => 'nc','active' => 1],
            ['id' => 149,'name' => 'Niger','code' => 'ne','active' => 1],
            ['id' => 150,'name' => 'Norfolk Island','code' => 'nf','active' => 1],
            ['id' => 151,'name' => 'Nigeria','code' => 'ng','active' => 1],
            ['id' => 152,'name' => 'Nicaragua','code' => 'ni','active' => 1],
            ['id' => 153,'name' => 'Netherlands','code' => 'nl','active' => 1],
            ['id' => 154,'name' => 'Norway','code' => 'no','active' => 1],
            ['id' => 155,'name' => 'Nepal','code' => 'np','active' => 1],
            ['id' => 156,'name' => 'Nauru','code' => 'nr','active' => 1],
            ['id' => 157,'name' => 'Niue','code' => 'nu','active' => 1],
            ['id' => 158,'name' => 'New Zealand (Aotearoa)','code' => 'nz','active' => 1],
            ['id' => 159,'name' => 'Oman','code' => 'om','active' => 1],
            ['id' => 160,'name' => 'Panama','code' => 'pa','active' => 1],
            ['id' => 161,'name' => 'Peru','code' => 'pe','active' => 1],
            ['id' => 162,'name' => 'French Polynesia','code' => 'pf','active' => 1],
            ['id' => 163,'name' => 'Papua New Guinea','code' => 'pg','active' => 1],
            ['id' => 164,'name' => 'Philippines','code' => 'ph','active' => 1],
            ['id' => 165,'name' => 'Pakistan','code' => 'pk','active' => 1],
            ['id' => 166,'name' => 'Poland','code' => 'pl','active' => 1],
            ['id' => 167,'name' => 'Saint Pierre and Miquelon','code' => 'pm','active' => 1],
            ['id' => 168,'name' => 'Pitcairn','code' => 'pn','active' => 1],
            ['id' => 169,'name' => 'Palestinian Territory','code' => 'ps','active' => 1],
            ['id' => 170,'name' => 'Portugal','code' => 'pt','active' => 1],
            ['id' => 171,'name' => 'Palau','code' => 'pw','active' => 1],
            ['id' => 172,'name' => 'Paraguay','code' => 'py','active' => 1],
            ['id' => 173,'name' => 'Qatar','code' => 'qa','active' => 1],
            ['id' => 174,'name' => 'Reunion','code' => 're','active' => 1],
            ['id' => 175,'name' => 'Romania','code' => 'ro','active' => 1],
            ['id' => 176,'name' => 'Russian Federation','code' => 'ru','active' => 1],
            ['id' => 177,'name' => 'Rwanda','code' => 'rw','active' => 1],
            ['id' => 178,'name' => 'Saudi Arabia','code' => 'sa','active' => 1],
            ['id' => 179,'name' => 'Solomon Islands','code' => 'sb','active' => 1],
            ['id' => 180,'name' => 'Seychelles','code' => 'sc','active' => 1],
            ['id' => 181,'name' => 'Sudan','code' => 'sd','active' => 1],
            ['id' => 182,'name' => 'Sweden','code' => 'se','active' => 1],
            ['id' => 183,'name' => 'Singapore','code' => 'sg','active' => 1],
            ['id' => 184,'name' => 'Saint Helena','code' => 'sh','active' => 1],
            ['id' => 185,'name' => 'Slovenia','code' => 'si','active' => 1],
            ['id' => 186,'name' => 'Svalbard and Jan Mayen','code' => 'sj','active' => 1],
            ['id' => 187,'name' => 'Slovakia','code' => 'sk','active' => 1],
            ['id' => 188,'name' => 'Sierra Leone','code' => 'sl','active' => 1],
            ['id' => 189,'name' => 'San Marino','code' => 'sm','active' => 1],
            ['id' => 190,'name' => 'Senegal','code' => 'sn','active' => 1],
            ['id' => 191,'name' => 'Somalia','code' => 'so','active' => 1],
            ['id' => 192,'name' => 'Suriname','code' => 'sr','active' => 1],
            ['id' => 193,'name' => 'Sao Tome and Principe','code' => 'st','active' => 1],
            ['id' => 194,'name' => 'El Salvador','code' => 'sv','active' => 1],
            ['id' => 195,'name' => 'Syria','code' => 'sy','active' => 1],
            ['id' => 196,'name' => 'Swaziland','code' => 'sz','active' => 1],
            ['id' => 197,'name' => 'Turks and Caicos Islands','code' => 'tc','active' => 1],
            ['id' => 198,'name' => 'Chad','code' => 'td','active' => 1],
            ['id' => 199,'name' => 'French Southern Territories','code' => 'tf','active' => 1],
            ['id' => 200,'name' => 'Togo','code' => 'tg','active' => 1],
            200 => ['id' => 201,'name' => 'Thailand','code' => 'th','active' => 1],
            201 => ['id' => 202,'name' => 'Tajikistan','code' => 'tj','active' => 1],
            202 => ['id' => 203,'name' => 'Tokelau','code' => 'tk','active' => 1],
            203 => ['id' => 204,'name' => 'Turkmenistan','code' => 'tm','active' => 1],
            204 => ['id' => 205,'name' => 'Tunisia','code' => 'tn','active' => 1],
            205 => ['id' => 206,'name' => 'Tonga','code' => 'to','active' => 1],
            206 => ['id' => 207,'name' => 'Turkey','code' => 'tr','active' => 1],
            207 => ['id' => 208,'name' => 'Trinidad and Tobago','code' => 'tt','active' => 1],
            208 => ['id' => 209,'name' => 'Tuvalu','code' => 'tv','active' => 1],
            209 => ['id' => 210,'name' => 'Taiwan','code' => 'tw','active' => 1],
            210 => ['id' => 211,'name' => 'Tanzania','code' => 'tz','active' => 1],
            211 => ['id' => 212,'name' => 'Ukraine','code' => 'ua','active' => 1],
            212 => ['id' => 213,'name' => 'Uganda','code' => 'ug','active' => 1],
            213 => ['id' => 214,'name' => 'Uruguay','code' => 'uy','active' => 1],
            214 => ['id' => 215,'name' => 'Uzbekistan','code' => 'uz','active' => 1],
            215 => ['id' => 216,'name' => 'Saint Vincent and the Grenadines','code' => 'vc','active' => 1],
            216 => ['id' => 217,'name' => 'Venezuela','code' => 've','active' => 1],
            217 => ['id' => 218,'name' => 'Virgin Islands (British)','code' => 'vg','active' => 1],
            218 => ['id' => 219,'name' => 'Virgin Islands (U.S.)','code' => 'vi','active' => 1],
            219 => ['id' => 220,'name' => 'Viet Nam','code' => 'vn','active' => 1],
            ['id' => 221,'name' => 'Vanuatu','code' => 'vu','active' => 1],
            ['id' => 222,'name' => 'Wallis and Futuna','code' => 'wf','active' => 1],
            ['id' => 223,'name' => 'Samoa','code' => 'ws','active' => 1],
            ['id' => 224,'name' => 'Yemen','code' => 'ye','active' => 1],
            ['id' => 225,'name' => 'Mayotte','code' => 'yt','active' => 1],
            ['id' => 226,'name' => 'South Africa','code' => 'za','active' => 1],
            ['id' => 227,'name' => 'Zambia','code' => 'zm','active' => 1],
            ['id' => 228,'name' => 'Zaire (former)','code' => 'zr','active' => 1],
            ['id' => 229,'name' => 'Zimbabwe','code' => 'zw','active' => 1],
            ['id' => 230,'name' => 'United States of America','code' => 'us','active' => 1],
        ));

        
    }
}